# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Add comment
on:
  issues:
    types: [opened, edited]

jobs:  
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Sentiment Analysis
        id: sa
        uses: oscarnevarezleal/issue-chill@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: "oscarnevarezleal"
          repo: "sample-repo"
          issue: ${{ github.event.issue.number }}

      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Sentiment analysis: 
            - ${{ steps.sa.outputs.POS }}
            - ${{ steps.sa.outputs.IS_50_POS }}
            - ${{ steps.sa.outputs.IS_60_POS }}
            - ${{ steps.sa.outputs.IS_70_POS }}
            - ${{ steps.sa.outputs.IS_80_POS }}
            - ${{ steps.sa.outputs.IS_90_POS }}
            - ${{ steps.sa.outputs.NEG }}
            - ${{ steps.sa.outputs.IS_50_NEG }}
            - ${{ steps.sa.outputs.IS_60_NEG }}
            - ${{ steps.sa.outputs.IS_70_NEG }}
            - ${{ steps.sa.outputs.IS_80_NEG }}
            - ${{ steps.sa.outputs.IS_90_NEG }}
            - ${{ steps.sa.outputs.NEU }}
            - ${{ steps.sa.outputs.CMP }}

      - name: Add positive comment
        if: ${{ startsWith(steps.sa.outputs.IS_60_POS, 'true') }}
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            > ${{ github.event.issue.number }}
            This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles:

      - name: Add negative reaction
        if: ${{ startsWith(steps.sa.outputs.IS_60_NEG, 'true') }}
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            > ${{ github.event.issue.number }}
            > "This Aggression Will Not Stand, Man."
